apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rcy9t2929-python 
  janus-idp.io/tekton: rcy9t2929-python
  backstage.io/kubernetes-id: rcy9t2929-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rcy9t2929-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml